# Generated by Django 2.2 on 2019-04-26 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('completed_form', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
